model_select: "cd_mvgnn"
force_field: 'uff'

encoder_atom: "cgcnn"
encoder_bond: "dim_14"

pooling: 'mean'
loss_sclect: 'bce'
grid_feat: 1
num_layers: 3
dropout_ratio: 0.0
feat_dim: 256
ffn_num_layers: 2
dist_coff: 0.1

LR: 0.0001
NUM_EPOCHS: 501
batch_size: 128
train_ratio: 0.8
vali_ratio: 0.1
test_ratio: 0.1
iter: 1
