model_select: "ka_gnn_two"
force_field: 'uff'

encoder_atom: "cgcnn"
encoder_bond: "dim_14"

pooling: 'avg'
loss_sclect: 'bce'
grid_feat: 1
num_layers: 4

LR: 0.0001
NUM_EPOCHS: 500
batch_size: 128
train_ratio: 0.8
vali_ratio: 0.1
test_ratio: 0.1
iter: 1
