model_select: "pretrain_gnn"
force_field: 'uff'

encoder_atom: "cgcnn"
encoder_bond: "dim_14"

pooling: 'mean'
loss_sclect: 'bce'
grid_feat: 1
num_layers: 5
dropout_ratio: 0.5

LR: 0.001
NUM_EPOCHS: 501
batch_size: 128
train_ratio: 0.8
vali_ratio: 0.1
test_ratio: 0.1
iter: 1
